name: Actions Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
      - run: python3 test.py  ${{ github.actor }}

      - name: Commit and push changes
        run: |
          git config --global user.name "riseusertest"
          git config --global user.email "riseusertest@gmail.com"

          git add -A
          git commit -m "Auto-updated master export"
          git push
        
      
